//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vintage_World.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellRequest
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Kms { get; set; }
        public Nullable<decimal> EnginLitres { get; set; }
        public string Transmission { get; set; }
        public string Fuel_Type { get; set; }
        public string IsUsed { get; set; }
        public string Color { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Image { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
