//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vintage_World.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldCar
    {
        public int Id { get; set; }
        public Nullable<int> Customer_Name { get; set; }
        public Nullable<int> Car_Detail { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
